### ISSUE TITLE
("phooks.ext") not running

### ISSUE THREAD

**Issue by Weeeishy** [Bara/BlockSMPlugins#1]
Hi,

First of all I would like to thank you for releasing that plugin in the public, while others are selling it.

I've installed the plugin, and extracted the phooks for windows and also installed them. However I'm getting this error.

`sm_plugins_block_phook.smx: Required extension "PHooks" file("phooks.ext") not running`

My OS is Windows.

Thank you again.

**Comment by nhnkl159** [comment]
same for me

**Comment by Bara** [comment]
On Windows or Linux @nhnkl159 ?

**Comment by nhnkl159** [comment]
@Bara20 On windows.

**Comment by Weeeishy** [comment]
Is there any work around or potential fix to that?

Thanks

**Comment by rogeraabbccdd** [comment]
Hello
Looks like CSGO update today break phooks
I'm using Linux with SM1.8-5954

> L 11/29/2016 - 13:44:20: [SM] Unable to load extension "phooks.ext": Failed to get > HandleCommand_Buy_Internal address
> L 11/29/2016 - 13:44:20: [SM] Unable to load plugin "sm_plugins_block_phook.smx": Required extension "PHooks" file("phooks.ext") not running

**Comment by Bara** [comment]
I'll take a look later, if i've more time for this.
