### ISSUE TITLE
Crash with last DEV sm

### ISSUE THREAD

**Issue by rajkodev** [Bara/BlockSMPlugins#11]
Server is running under windows server 2016, latest PtaH and latest SM dev version 1.10+.

Server is just crashing without any logs, and when i disable this plugin its works perfect.
Is there any way to fix this problem?

Check here windows changes:

https://github.com/komashchenko/PTaH/issues/15

**Comment by Bara** [comment]
Try latest PTaH (Version 1.1.0) with latest smx file.
