### ISSUE TITLE
Nachricht wird nicht angezeigt

### ISSUE THREAD

**Issue by freakexeuLow** [Bara/BlockSMPlugins#15]
Abend Bara, wenn ich versuche mit einem normalen Account in der Console den Befehl zB "sm plugins" eingebe, erscheint die Meldung nicht: This command was blocked for public viewing. Und nein, eine error.log ist nicht vorhanden und hättest du noch eine Ahnung woran es liegen könnte?^^
> PTAH 1.10
> SM 1.10

**Comment by Bara** [comment]
und `sbp_allow_rootadmin`ist auch auf 1?

**Comment by freakexeuLow** [comment]
Am Plugin habe ich nicht weiter was geändert und die Plugins werden schon nicht gezeigt das soll ja so sein, Problem war nur das die Nachricht "This command was blocked for public viewing" nicht erscheint bzw glaube ich erst seit dem Update auf 1.10 PTAH hab das davor nicht getestet.

**Comment by Bara** [comment]
Sowie ich gerade gesehen habe, wird die Translation "SMPlugin" nicht mehr benutzt. Sicher, dass du letzte Version hier von Github (PTaH oder DHooks) verwendest?

**Comment by freakexeuLow** [comment]
Ja, ich nutze die neuste Version und nutze PTAH und hab noch die Translation drin, ich werde es mal morgen ohne probieren und dir schreiben ob es klappt oder nicht. Bin nun am mein Handy und hab schon den Pc ausgemacht.

**Comment by freakexeuLow** [comment]
Guten Morgen und die Translation File wird noch bei mir benötigt...sobald ich diese entferne, wird mir ein Fehler in der Log angezeigt das diese nicht vorhanden ist. DHOOKS Version von Sbp klappt bei mir gar nicht, da angeblich gesagt wird das ich dhooks.ext nicht habe, aber was nicht so ganz stimmt da ich es für den SurfTimer benötige.
[https://i.gyazo.com/87f782d3d34dd7d280aa9e8fdfe0b690.png](https://i.gyazo.com/87f782d3d34dd7d280aa9e8fdfe0b690.png)

Hab das Foto mit mein Smurf gemacht der keine Rechte hat, wie oben schon geschrieben wird mir danach keine Meldung angezeigt. Geht das den bei dir auf dem Server?

EDIT: Es wurde die Version Dhooks 2.2 verwendet

**Comment by freakexeuLow** [comment]
Danke und okay, hab ich mal gemacht, trotzdem wird dein Stinkefinger und das No Chance erst gar nicht angezeigt. Getestet wurde das mit einem Smurf der kein Admin oder sonstiges hat.

**Comment by asdfxD** [comment]
Ist auf meinem Server genauso, seit Update wird nichts mehr geloggt wer die Commands eingibt.

Auf einem anderen Server von mir läuft noch eine ältere Version von SM und ptah, dort wird geloggt.

SourceMod Version: 1.9.0.6276
PTaH (P Tools and Hooks) (1.0.10)

**Comment by freakexeuLow** [comment]
Gut zu wissen, ich dachte schon das ich irgendwas verkackt habe^^

**Comment by Bara** [comment]
Hab es damals zum testen entfernt bzgl. Crashs eingrenzen.

**Comment by freakexeuLow** [comment]
> Hab es damals zum testen entfernt bzgl. Crashs eingrenzen.

Okay, gut zu wissen, dachte es sei beim Update kaputt gegangen. Werde das Thema hier schließen, ist ja nun aufgeklärt warum es nicht mehr geht
