### ISSUE TITLE
Compatible with latest PTaH?

### ISSUE THREAD

**Issue by crashzk** [Bara/BlockSMPlugins#17]
I would like to know if it is compatible with the latest version of PTaH: https://ptah.zizt.ru/

I have the latest on my server and is giving the following error:
```
Errors:
sbp.smx: Error detected in plugin startup (see error logs)
```
However in the most recent error logs does not show any errors:
[errors_20191215.log](https://github.com/Bara/BlockSMPlugins/files/3965134/errors_20191215.log)

**Comment by Bara** [comment]
It should be compatible with latest PTaH Version.

https://github.com/Bara/BlockSMPlugins/commit/7d2f58c52e0e1b20ec8e5c452c62525336100bb6

**Comment by Bara** [comment]
And I can't see any related logs with "sbp.smx" in your provided log file.
