### ISSUE TITLE
Change the message that displays when the player tries to use the commands

### ISSUE THREAD

**Issue by crashzk** [Bara/BlockSMPlugins#18]
It would be intense to include a CVAR so that we can choose which message to display when a player tries to use one of the commands

Currently shows the following message:
https://github.com/Bara/BlockSMPlugins/blob/7286255efcf4c9b4d7baf062901855da648f0280/PTaH/scripting/sbp.sp#L55-L84

That way you could choose from CVAR which message would be displayed. I think it's even better than creating a translation file for that

**Comment by skibz** [comment]
haha 👍

**Comment by Bara** [comment]
Done
