### ISSUE TITLE
kEconItemFlag_CannotTrade - undefined symbol

### ISSUE THREAD

**Issue by JustZerooo** [Bara/BlockSMPlugins#21]
```

//// sbp.sp
//
// C:\Users\Operator\Desktop\TestServerCsGo\addons\sourcemod\scripting\include\PTaH.inc(77) : error 017: undefined symbol "kEconItemFlag_CannotTrade"
// C:\Users\Operator\Desktop\TestServerCsGo\addons\sourcemod\scripting\include\PTaH.inc(80) : error 017: undefined symbol "kEconItemFlags_CheckFlags_CannotTrade"
// C:\Users\Operator\Desktop\TestServerCsGo\addons\sourcemod\scripting\include\PTaH.inc(81) : error 021: symbol already defined: "kEconItemFlag_CannotTrade"
//
// 3 Errors.
//
// Compilation Time: 0,19 sec
// ----------------------------------------
```

**Comment by Bara** [comment]
I can't reproduce this. Update your include ptah.inc from https://ptah.zizt.ru/

**Comment by JustZerooo** [comment]
I did and i get this error. Check again!

**Comment by JustZerooo** [comment]
https://streamable.com/ei9ht2

**Comment by Bara** [comment]
That's a issue (or bug?) with the SM 1.11 compiler (which you didn't notice that, I just test it with SM1.10) which isn't stable yet. Switch (back) to the SM1.10 compiler or create a issue [here](https://github.com/komashchenko/PTaH/issues) (or maybe @komashchenko read this) . From AlliedModders you'll get no help for this kind of stuff or you create a example plugin without the functions that can block sourcemod commands.
