### ISSUE TITLE
Updated needed. csgo update 11/28/16

### ISSUE THREAD

**Issue by asdfxD** [Bara/BlockSMPlugins#4]
extension is outdated i think, it is not working anymore.

[SM] Unable to load extension "phooks.ext": Failed to get HandleCommand_Buy_Internal address

**Comment by Bara** [comment]
https://github.com/Bara20/BlockSMPlugins/issues/1#issuecomment-263598006

**Comment by Bara** [comment]
Updated and read the README file ( you need now PTaH ).
