### ISSUE TITLE
Crash when bots in server

### ISSUE THREAD

**Issue by rogeraabbccdd** [Bara/BlockSMPlugins#5]
This [commit](https://github.com/Bara20/BlockSMPlugins/commit/85da93bcd60fd4b3f2f1e894f6b8ddab61a3d3f4) didn't fix the problem, my server is still crashing.

when I type "sm_rcon bot_kick", my server crash and these are error logs
>L 12/01/2016 - 17:46:33: [SM] Exception reported: Client index 66699873 is invalid
>L 12/01/2016 - 17:46:33: [SM] Blaming: sbp.smx
>L 12/01/2016 - 17:46:33: [SM] Call stack trace:
>L 12/01/2016 - 17:46:33: [SM]   [0] IsFakeClient
>L 12/01/2016 - 17:46:33: [SM]   [1] Line 37, D:\SourcePawn\Projects\BlockSMPlugins\scripting\sbp.sp::ConsolePrint
>L 12/01/2016 - 17:46:33: [SM]   [3] ReplyToCommand
>L 12/01/2016 - 17:46:33: [SM]   [4] Line 391, /home/builds/sourcemod/linux-1.8/build/plugins/basecommands.sp::Command_Rcon

SM 1.8-5961

**Comment by rogeraabbccdd** [comment]
My server stil crash :(

**Comment by Headline** [comment]
The error shouldn't be the same. Can you post a newer stack trace?

**Comment by rogeraabbccdd** [comment]
Problem sloved, I don't know why.
