### ISSUE TITLE
CSGO Update

### ISSUE THREAD

**Issue by Czar-VG** [Bara/BlockSMPlugins#8]
Since update last night, plugin causes seg fault.

**Comment by Bara** [comment]
This should work
[PTaH.ext.2.csgo.so.zip](https://github.com/Bara20/BlockSMPlugins/files/959169/PTaH.ext.2.csgo.so.zip)
[PTaH.ext.2.csgo.dll.zip](https://github.com/Bara20/BlockSMPlugins/files/959171/PTaH.ext.2.csgo.dll.zip)
